receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"  
      http:

processors:
  batch:

exporters:
  kafka:
    brokers: ["kafka:9092"]
    topic: otel-spans

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [kafka]
