receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:55681"

exporters:
  otlp:
    endpoint: "jaeger-collector:14250"
    tls:
      insecure: true  # Disable TLS verification for local setup

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [otlp]
